swagger: '2.0'
info:
  title: Sojobo API
  description: Sojobo API
  version: "1.0.1"
# the domain of the service
host: tengu.io
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /:
    get:
      summary: Hello World
      responses:
        200:
          description: Info about the API
          schema:
            type: array
            items:
              $ref: '#/definitions/ApiInfo'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/{username}:
    put:
      summary: Create a user
      parameters:
        - name: username
          in: path
          required: true
          type: string
        - name: user creation object
          in: body
          required: true
          schema:
            $ref: '#/definitions/UserCreationObj'
      responses:
        200:
          description: Info about the call
          schema:
            $ref: '#/definitions/Message'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /users/{username}/{modelname}:
    put:
      summary: Create a model
      parameters:
        - name: username
          in: path
          required: true
          type: string
        - name: modelname
          in: path
          required: true
          type: string
      responses:
        200:
          description: Info about the call
          schema:
            $ref: '#/definitions/Message'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  ApiInfo:
    type: object
    properties:
      version:
        type: string
        description: semver.org formatted string that denotes the api version
      name:
        type: string
        description: Hostname of the server
  Message:
    type: object
    properties:
      message:
        type: string
        description: Human readable message that explains what happened.
  UserCreationObj:
    type: object
    properties:
      version:
        type: string
        description: semver.org formatted string that denotes the api version
      name:
        type: string
        description: Hostname of the server
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
