#!/usr/bin/python3
# pylint: disable=c0111,c0103
import amulet
d = amulet.Deployment(series='trusty')
d.add('hauchiwa')
d.add('rest2jfed', charm="local:trusty/rest2jfed")
d.relate('hauchiwa:rest2jfed', 'rest2jfed:rest2jfed')
try:
    # Create the deployment described above, give us 900 seconds to do it
    d.setup(timeout=900)
    # Setup will only make sure the services are deployed, related, and in a
    # "started" state. We can employ the sentries to actually make sure there
    # are no more hooks being executed on any of the nodes.
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    # Something else has gone wrong, raise the error so we can see it and this
    # will automatically "FAIL" the test.
    raise
# Shorten the names a little to make working with unit data easier
hauchiwa_unit = d.sentry['hauchiwa'][0]
rest2jfed_unit = d.sentry['rest2jfed'][0]
