#!/bin/bash -e

installPackages()
{
	juju-log "Installing Packages"
	apt-get -y install git
	apt-get -y install maven
	apt-get -y install openjdk-7-jdk
	if [ ! -d "/tmp/storm-topology" ]; then
		juju-log "Creating /tmp/storm-topology"
		mkdir -p /tmp/storm-topology
	fi
	if [ ! -f "/tmp/storm-topology/bolt-list" ]; then
		juju-log "Creating bolt-list"
		touch -p /tmp/storm-topology/bolt-list
	fi
	status-set blocked "Waiting for: bolt class"
}

getBolt()
{
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topology=`grep "^$serviceName" /tmp/storm-topology/spout-list | cut -d " " -f 2`
	juju-log "Downloading bolt"
	className=${$2##*/}
	classNoExtension=`echo $className | cut -d \. -f1`
	wget $1 /tmp/storm-topology/$topology/Storm-Skeleton/src/main/java/tengu/storm/$className
	echo "$serviceName $classNoExtension" >> /tmp/storm-topology/$topology/bolts
	status-set active
	#call run-topology
}

checkSettings()
{
	#boltName=`config-get name`
	boltClass=`config-get boltClass`
	waitingFor=""
	#if [ -w $boltName ];then
	#	waitingFor="$waitingFor; bolt name"
	#fi
	if [ -w $boltClass ];then
		waitingFor="$waitingFor; bolt class"
	fi
	if [ -w $waitingFor ];then
		getBolt $boltClass
	else
		status-set blocked "Waiting for $waitingFor"
	fi
	waitingFor=""
}

topologyChanged()
{
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topologyName=`relation-get serviceName`
	juju-log "Topology name is: $topologyName"	
	#grep -q "^$serviceName" /tmp/storm-topology/spout-list && sed -i --quiet "s/^$serviceName.*/$serviceName $topologyName/" /tmp/storm-topology/bolt-list || echo "$serviceName $topologyName" >> /tmp/storm-topology/bolt-list

	if [ grep -q "^$serviceName" /tmp/storm-topology/bolt-list ];then
		hulp=$(sed --quiet "s/^$serviceName.*/$serviceName $topologyName/" /tmp/storm-topology/bolt-list)
		echo "$hulp" > /tmp/storm-topology/bolt-list
	else
		echo "$serviceName $topologyName" >> /tmp/storm-topology/bolt-list
	fi
}

stormelementChanged()
{
	juju-log "stormelement relation changed"
	serviceName=`[[ "$(pwd)" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	relation-set elementName=$serviceName
	topology=`grep "^$serviceName" /tmp/storm-topology/spout-list | cut -d " " -f 2`
	element=`relation-get elementName`
	if [ -w element ]; then
		juju-log "Connected to: $element"
		#check if already in graph
		( grep "$serviceName" /tmp/storm-topology/$topology/graph | grep -q "$element" ) || echo "$serviceName $element SHUFFLE" >> /tmp/storm-topology/$topology/graph
		#deploy new graph
	fi
}

cmd=$(basename "$0")
case $cmd in
config-changed)
	;;
install)
	installPackages
	;;
start)
	;;
stop)
	;;
upgrade-charm)
	;;
topology-relation-changed)
	topologyChanged
	;;
stormelement-relation-changed)
	stormelementChanged
esac
