#!/bin/bash -e

installPackages()
{
	juju-log "Installing Packages"
	apt-get -y install git
	apt-get -y install maven
	apt-get -y install openjdk-7-jdk
	if [ ! -d "/tmp/storm-topology" ]; then
		juju-log "Creating /tmp/storm-topology"
		mkdir -p /tmp/storm-topology
	fi
	if [ ! -f "/tmp/storm-topology/bolt-list" ]; then
		juju-log "Creating bolt-list"
		touch /tmp/storm-topology/bolt-list
	fi
	status-set blocked "Waiting for: bolt class"
}

getBolt()
{
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topology=`grep "^$serviceName" /tmp/storm-topology/bolt-list | cut -d " " -f 2`
	juju-log "Downloading bolt"
	className=${1##*/}
	classNoExtension=`echo $className | cut -d \. -f1`
	if [ ! -f /tmp/storm-topology/$topology/Storm-Flux-Skeleton/src/main/java/tengu/storm/$className ]; then
		wget -nc "$1" -P /tmp/storm-topology/$topology/Storm-Flux-Skeleton/src/main/java/tengu/storm
		sed -i "s/.*package.*/package tengu.storm;/" /tmp/storm-topology/$topology/Storm-Flux-Skeleton/src/main/java/tengu/storm/$className
		echo "$classNoExtension 1" >> /tmp/storm-topology/$topology/classes
		echo "1" > /tmp/storm-topology/$topology/rebuild
	else
		classnr=$(grep "$classNoExtension" /tmp/storm-topology/$topology/classes | cut -d " " -f 2)
		((classnr++))
		sed -i "s/^$classNoExtension.*/$classNoExtension $classnr/" /tmp/storm-topology/$topology/classes
	fi
	echo "$serviceName $classNoExtension" >> /tmp/storm-topology/$topology/bolts
	status-set active
}

checkSettings()
{
	boltClass=`config-get class`
	if [ -n "$boltClass" ]; then
		juju-log "Getting class"
		getBolt $boltClass
	else
		juju-log "bolt class required"
		status-set blocked "Waiting for class"
	fi	
}

topologyChanged()
{
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topologyName=`relation-get serviceName`
	juju-log "Topology name is: $topologyName"
	if grep -q "^$serviceName" /tmp/storm-topology/bolt-list ; then
		hulp=$(sed "s/^$serviceName.*/$serviceName $topologyName/" /tmp/storm-topology/bolt-list)
		juju-log "Copy bolt-list "
		#juju-log "$hulp"
		echo "$hulp" > /tmp/storm-topology/bolt-list
	else	
		juju-log "Bolt not found in bolt-list ... adding"
		echo "$serviceName $topologyName" >> /tmp/storm-topology/bolt-list
	fi
}

stormelementChanged()
{
	juju-log "stormelement relation changed"
	serviceName=`[[ "$(pwd)" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	relation-set elementName=$serviceName
	topology=`grep "^$serviceName" /tmp/storm-topology/bolt-list | cut -d " " -f 2`
	element=`relation-get elementName`
	if [ -n "$element" ]; then
		juju-log "Connected to: $element"
		#check if already in graph
		( grep -w "$serviceName" /tmp/storm-topology/$topology/graph | grep -wq "$element" ) || echo "$serviceName $element SHUFFLE" >> /tmp/storm-topology/$topology/graph
		#deploy new graph
		/bin/bash /tmp/storm-topology/buildGraph $topology
		juju-log "Ready to deploy topology.yaml"
	fi
}

cmd=$(basename "$0")
case $cmd in
config-changed)
	checkSettings
	;;
install)
	installPackages
	;;
start)
	;;
stop)
	;;
upgrade-charm)
	;;
topology-relation-changed)
	topologyChanged
	;;
stormelement-relation-changed)
	stormelementChanged
	;;
boltworker-relation-changed)
	stormelementChanged
	;;
esac
