"options":
  "extra_packages":
    "description": "Space separated list of extra deb packages to install.\n"
    "type": "string"
    "default": ""
  "package_status":
    "default": "install"
    "type": "string"
    "description": "The status of service-affecting packages will be set to this value\
      \ in the dpkg database. Valid values are \"install\" and \"hold\".\n"
  "install_sources":
    "description": "List of extra apt sources, per charm-helpers standard format (a\
      \ yaml list of strings encoded as a string). Each source may be either a line\
      \ that can be added directly to sources.list(5), or in the form ppa:<user>/<ppa-name>\
      \ for adding Personal Package Archives, or a distribution component to enable.\n"
    "type": "string"
    "default": ""
  "install_keys":
    "description": "List of signing keys for install_sources package sources, per\
      \ charmhelpers standard format (a yaml list of strings encoded as a string).\
      \ The keys should be the full ASCII armoured GPG public keys. While GPG key\
      \ ids are also supported and looked up on a keyserver, operators should be aware\
      \ that this mechanism is insecure. null can be used if a standard package signing\
      \ key is used that will already be installed on the machine, and for PPA sources\
      \ where the package signing key is securely retrieved from Launchpad.\n"
    "type": "string"
    "default": ""
  "puppet-gpg-key":
    "type": "string"
    "description": |
      Puppet gpg key used to configure Puppetlabs apt sources. You can find
      and verify this key at https://apt.puppetlabs.com/DEB-GPG-KEY-puppet
    "default": |
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQINBFe2Iz4BEADqbv/nWmR26bsivTDOLqrfBEvRu9kSfDMzYh9Bmik1A8Z036Eg
      h5+TZD8Rrd5TErLQ6eZFmQXk9yKFoa9/C4aBjmsL/u0yeMmVb7/66i+x3eAYGLzV
      FyunArjtefZyxq0B2mdRHE8kwl5XGl8015T5RGHCTEhpX14O9yigI7gtliRoZcl3
      hfXtedcvweOf9VrV+t5LF4PrZejom8VcB5CE2pdQ+23KZD48+Cx/sHSLHDtahOTQ
      5HgwOLK7rBll8djFgIqP/UvhOqnZGIsg4MzTvWd/vwanocfY8BPwwodpX6rPUrD2
      aXPsaPeM3Q0juDnJT03c4i0jwCoYPg865sqBBrpOQyefxWD6UzGKYkZbaKeobrTB
      xUKUlaz5agSK12j4N+cqVuZUBAWcokXLRrcftt55B8jz/Mwhx8kl6Qtrnzco9tBG
      T5JN5vXMkETDjN/TqfB0D0OsLTYOp3jj4hpMpG377Q+6D71YuwfAsikfnpUtEBxe
      NixXuKAIqrgG8trfODV+yYYWzfdM2vuuYiZW9pGAdm8ao+JalDZss3HL7oVYXSJp
      MIjjhi78beuNflkdL76ACy81t2TvpxoPoUIG098kW3xd720oqQkyWJTgM+wV96bD
      ycmRgNQpvqHYKWtZIyZCTzKzTTIdqg/sbE/D8cHGmoy0eHUDshcE0EtxsQARAQAB
      tEhQdXBwZXQsIEluYy4gUmVsZWFzZSBLZXkgKFB1cHBldCwgSW5jLiBSZWxlYXNl
      IEtleSkgPHJlbGVhc2VAcHVwcGV0LmNvbT6JAj4EEwECACgFAle2Iz4CGwMFCQlm
      AYAGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEH9DgoDvjTSfIN0P/jcCRzK8
      WIdhcNz5dkj7xRZb8Oft2yDfenQmzb1SwGGa96IwJFcjF4Nq7ymcDUqunS2DEDb2
      gCucsqmW1ubkaggsYbc9voz/SQwhsQpBjfWbuyOX9DWmW6av/aB1F85wP79gyfqT
      uidTGxQE6EhDbLe7tuvxOHfM1bKsUtI+0n9TALLLHfXUEdtaXCwMlJuO1IIn1PWa
      H7HzyEjw6OW/cy73oM9nuErBIio1O60slPLOW2XNhdWZJCRWkcXyuumRjoepz7WN
      1JgsLOTcB7rcQaBP3pDN0O/Om5dlDQ6oYitoJs/F0gfEgwK68Uy8k8sUR+FLLJqM
      o0CwOg6CeWU4ShAEd1xZxVYW6VOOKlz9x9dvjIVDn2SlTBDmLS99ySlQS57rjGPf
      GwlRUnuZP4OeSuoFNNJNb9PO6XFSP66eNHFbEpIoBU7phBzwWpTXNsW+kAcY8Rno
      8GzKR/2FRsxe5Nhfh8xy88U7BA0tqxWdqpk/ym+wDcgHBfSRt0dPFnbaHAiMRlgX
      J/NPHBQtkoEdQTKA+ICxcNTUMvsPDQgZcU1/ViLMN+6kZaGNDVcPeMgDvqxu0e/T
      b3uYiId38HYbHmD6rDrOQL/2VPPXbdGbxDGQUgX1DfdOuFXw1hSTilwI1KdXxUXD
      sCsZbchgliqGcI1l2En62+6pI2x5XQqqiJ7+
      =HpaX
      -----END PGP PUBLIC KEY BLOCK-----
  "key-country":
    "type": "string"
    "default": "US"
    "description": "Country field for RSA certificate."
  "key-province":
    "type": "string"
    "default": "CA"
    "description": "Province field for RSA certificate."
  "key-city":
    "type": "string"
    "default": "Ubuntu"
    "description": "City field for RSA certificate."
  "key-org":
    "type": "string"
    "default": "Juju"
    "description": "Organization field for RSA certificate."
  "key-email":
    "type": "string"
    "default": "Juju"
    "description": "Email field for RSA certificate."
  "clients":
    "type": "string"
    "default": "client1"
    "description": "Space-separated list with names of users to generate config for."
  "port":
    "type": "int"
    "default": !!int "443"
    "description": "Port for VPN traffic. Default is 443 since it isn't likely to\
      \ be blocked by the firewall."
  "protocol":
    "type": "string"
    "default": "tcp"
    "description": "Protocol for VPN communication (tcp|udp). Tcp on port 443 is least\
      \ likely to be blocked by firewalls. Udp on port 1194 is fastest."
  "duplicate-cn":
    "type": "boolean"
    "default": !!bool "true"
    "description": "Will multiple users connect using the same client config? (yes\
      \ = True)"
  "push-dns":
    "type": "boolean"
    "default": !!bool "true"
    "description": "Should the connecting clients use the same DNS and search domain\
      \ as the OpenVPN server? (yes = True)"
  "push-default-gateway":
    "type": "boolean"
    "default": !!bool "true"
    "description": |
      Should the connecting clients use the VPN server for ALL connections? (yes = True) If this is False, the VPN will only be used for connections to the internal network. Connections to the internet will still use the client's existing non-vpn connection. Note: NetworkManager always sets the VPN as default gateway, regardless of this setting. To change this behavior: Click NetworkManager applet icon > VPN Connections > Configure VPN... > select VPN network > Edit > IPv4 Settings > Routes... > Check 'Use this connection only for resources on its network'
