#!/usr/bin/env python
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from charmhelpers.core.hookenv import related_units, relation_get
from zkutils import update_zoo_cfg, getid

nodeList = related_units()
for n in nodeList:
    unitIP = relation_get('private-address', unit=n)
    zk = os.path.join(os.path.sep, os.environ.get('ZOOCFGDIR', '/etc/zookeeper/conf'), 'zoo.cfg')
    update_zoo_cfg(zkid=getid(n), ip=unitIP)
