#!/usr/bin/env python
#pylint: disable=C0103,c0111,c0325
import sys
import os
sys.path.append(os.path.realpath(os.path.dirname(__file__) + '/../hooks/'))

try:
    import callbacks
    import jujubigdata
    from charmhelpers.core import unitdata
    charm_ready = unitdata.kv().get('charm.active', False)
except ImportError:
    print('import failed')
    charm_ready = False

if not charm_ready:
    # might not have hookenv.action_fail available yet
    from subprocess import call
    call(['action-fail', 'Kafka service not yet ready'])


kafka_reqs = ['vendor', 'packages', 'groups', 'users', 'dirs', 'ports']
dist_config = jujubigdata.utils.DistConfig(filename='dist.yaml',
                                           required_keys=kafka_reqs)
kafka = callbacks.Kafka(dist_config)
kafka.stop()
