#!/usr/bin/env python
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
All hooks in this charm are managed by the Charm Framework.
The framework helps manage dependencies and preconditions to ensure that
steps are only executed when they can be successful.  As such, no additional
code should be added to this hook; instead, please integrate new functionality
into the 'callbacks' list in hooks/common.py.  New callbacks can be placed
in hooks/callbacks.py, if necessary.

See http://big-data-charm-helpers.readthedocs.org/en/latest/examples/framework.html
for more information.
"""
import common
common.manage()
