"options":
  "database":
    "type": "string"
    "default": "testdb"
    "description": |
      Name of the MongoDB database that the segment will connect to.
  "installable-id":
    "type": "string"
    "default": "org.ibcn.limeds.mongodb"
    "description": |
      Id of the MongoDB connector installable. List of available installables: http://limeds.be/installables.
  "installable-version":
    "type": "string"
    "default": "latest"
    "description": |
      Version of the MongoDB connector installable. List of available installables: http://limeds.be/installables.
  "segment-id":
    "type": "string"
    "default": "io.tengu.limeds.MongoDB"
    "description": |
      Id of the MongoDB segment that will be created in LimeDS. Your slices can refer to the segment using this id.
