options:
  name:
    default: TopologyName
    type: string
    description: "Specify name of topology"    
  dependencies:
    default:
    type: string 
    description: "URL to dependencies file"    

