options:
  name:
    type: string
    default: TopologyName    
    description: |
      Specify name of topology   
  dependencies:
    type: string 
    default:    
    description: |
      URL to dependencies file   

