options:
  name:
    type: string
    description: "Specify name of topology"
    default: TopologyName
  dependencies: string
    default:
    description: "URL to dependencies file"
    type: string 

