#!/usr/bin/python3

import unittest
import amulet


class TestDeploy(unittest.TestCase):
    """
    Deployment test for Apache Zookkepper quorum
    """

    @classmethod
    def setUpClass(cls):
        cls.d = amulet.Deployment(series='trusty')

        cls.d.add('zookeeper', charm='cs:~bigdata-dev/trusty/apache-zookeeper', units=3)
         
        cls.d.setup(timeout=9000)
        cls.d.sentry.wait()
        cls.unit = cls.d.sentry.unit['zookeeper/0']

    def test_deploy(self):
        output, retcode = self.unit.run("pgrep -a java")
        assert 'QuorumPeerMain' in output, "zookeeper QuorumPeerMain daemon is not started"


if __name__ == '__main__':
    unittest.main()