options:
  proxy:
    default:
    type: "string"
    description: "Proxy to use when fetching resources from PyPI, if not already set in Juju"
  juju-user:
    default: "user-admin"
    type: "string"
    description: "Juju API User"
  juju-secret:
    default: ""
    type: "string"
    description: "Juju Secret for API User"
  publish-url:
    default: ""
    type: "string"
    description: >
      "The url to which benchmark results can be published,
      e.g., http://cloud-benchmarks.org/submissions. Leave
      blank to disable publishing."
