"options":
  "charm-repo-source":
    "type": "string"
    "description": "Git url where charm repo resides. Expects charm repo in <repo_root>/charms."
    "default": !!null ""
  "environment-name":
    "type": "string"
    "description": "Name of the environment to configure"
    "default": !!null ""
  "environment-config":
    "type": "string"
    "description": "base64 encoded environment config from environments.yaml"
    "default": !!null ""
  "environment-jenv":
    "type": "string"
    "description": "base64 encoded environment.jenv file"
    "default": !!null ""
  "environment-pubkey":
    "type": "string"
    "description": "base64 encoded pubkey file"
    "default": !!null ""
  "environment-privkey":
    "type": "string"
    "description": "base64 encoded privkey file"
    "default": !!null ""
  "ssh-keys":
    "type": "string"
    "description": "a comma-seperated list of public ssh keys to add to the default\
      \ (admin) user. The keys must be in the authorized-keys format. \"ssh-rsa <key>\
      \ <comment>\"."
    "default": !!null ""
  "user":
    "type": "string"
    "default": "ubuntu"
    "description": "user to install the tools for"
