"options":
  "resources_mirror":
    "type": "string"
    "default": ""
    "description": |
      URL from which to fetch resources (e.g., Hadoop binaries) instead of Launchpad.
  "ganglia_metrics":
    "type": "boolean"
    "default": !!bool "false"
    "description": |
      Enable metrics using Ganglia, if related to the Ganglia charm via the
      ganglia:master relation.  The Hadoop services *will* be restarted if
      this option is enabled and the Ganglia service is related.
  "dfs_blocksize":
    "type": "int"
    "default": !!int "134217728"
    "description": |
      The default block size for new files (default to 64MB). Increase
      this in larger deployments for better large data set performance.
  "dfs_replication":
    "type": "int"
    "default": !!int "3"
    "description": |
      Default block replication. The actual number of replications can be
      specified when the file is created. The default is used if
      replication is not specified at file creation time.
