"options":
  "extra_packages":
    "description": "Space separated list of extra deb packages to install.\n"
    "type": "string"
    "default": ""
  "package_status":
    "default": "install"
    "type": "string"
    "description": "The status of service-affecting packages will be set to this value\
      \ in the dpkg database. Valid values are \"install\" and \"hold\".\n"
  "install_sources":
    "description": "List of extra apt sources, per charm-helpers standard format (a\
      \ yaml list of strings encoded as a string). Each source may be either a line\
      \ that can be added directly to sources.list(5), or in the form ppa:<user>/<ppa-name>\
      \ for adding Personal Package Archives, or a distribution component to enable.\n"
    "type": "string"
    "default": ""
  "install_keys":
    "description": "List of signing keys for install_sources package sources, per\
      \ charmhelpers standard format (a yaml list of strings encoded as a string).\
      \ The keys should be the full ASCII armoured GPG public keys. While GPG key\
      \ ids are also supported and looked up on a keyserver, operators should be aware\
      \ that this mechanism is insecure. null can be used if a standard package signing\
      \ key is used that will already be installed on the machine, and for PPA sources\
      \ where the package signing key is securely retrieved from Launchpad.\n"
    "type": "string"
    "default": ""
  "port":
    "type": "int"
    "default": !!int "80"
    "description": |
      NGINX listen port
  "host":
    "type": "string"
    "default": "127.0.0.1"
    "description": "listen address"
  "nginx":
    "default": !!bool "true"
    "type": "boolean"
    "description": "Configures nginx and gunicron for the flask application."
  "flask-port":
    "default": !!int "8000"
    "type": "int"
    "description": "Flask listening port"
  "string-option":
    "type": "string"
    "default": "Default Value"
    "description": "A short description of the configuration option"
  "boolean-option":
    "type": "boolean"
    "default": !!bool "false"
    "description": "A short description of the configuration option"
  "int-option":
    "type": "int"
    "default": !!int "9001"
    "description": "A short description of the configuration option"
