#!/bin/bash
set -e

juju-log "Importing shared variables and functions"
source hooks/common.sh


# Accept traffic from the tunnel interface and set up nat to all active interfaces
iptables -A INPUT -i tun+ -j ACCEPT
iptables -A FORWARD -i tun+ -j ACCEPT
INTERFACES=`ifconfig -a | sed 's/[ \t].*//;/^\(lo\|tun.\|veth.*\|\)$/d'`
for IFACE in ${INTERFACES}; do
  iptables -t nat -A POSTROUTING -s ${NETWORK} -o ${IFACE} -j MASQUERADE
done


# Ensure port settings are up to date | port from 1-65535
juju-log "Updating port and protocol settings"
sed -r -i -e "s/port [0-9]{1,5}.*/port ${PORT}/g" $SERVER_CONF
sed -r -i -e "s/proto (tcp|udp).*/proto ${PROTO}/g" $SERVER_CONF


# Generate client key
create_user 'client1'


# Restart OpenVPN services
juju-log "Restarting the OpenVPN service"
service openvpn stop || true
service openvpn start || ( echo "Failed to start OpenVPN" && exit 1 )
open-port ${PORT}/${PROTO}


# Great work, go take a break.
juju-log "Finished applying changes"
status-set active "Ready"
