#!/bin/bash
# based on: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-14-04
# based on: https://jujucharms.com/openvpn/precise/2
# based on: http://www.arm-blog.com/setting-up-a-openvpn-server/
set -e

juju-log "Importing shared variables and functions"
source hooks/common.sh

# install base packages
apt-get -y update
apt-get -y install openvpn easy-rsa

# copy default server config
gunzip -c /usr/share/doc/openvpn/examples/sample-config-files/server.conf.gz > $SERVER_CONF

# Allow multiple connections using single client
sed -i -e "s/;duplicate-cn/duplicate-cn/g" $SERVER_CONF
# Use bigger key
sed -i -e "s/dh dh1024.pem/dh dh2048.pem/g" $SERVER_CONF
grep -q '^option' file && sed -i 's/^option.*/option=value/' file || echo 'option=value' >> file

# Remove any prior active routes
sed -r -i -e '/push \"route ([0-9]{1,3}\.){3}.*\" # Managed by juju/d' $SERVER_CONF
# push route to client to route traffic to $NETWORK via VPN tunnel
echo "push \"route ${NETWORK}\" # Managed by juju" >> $SERVER_CONF


# Remove any prior active routes
juju-log "Removing old routes"
sed -r -i -e '/push \"route ([0-9]{1,3}\.){3}.*\"/d' $SERVER_CONF
# Route traffic destined to the $IFACE network via the VPN tunnel
juju-log "Adding current network route"
echo "push \"route ${current_network}\"" >> $SERVER_CONF
# Add user supplied additional routes
juju-log "Adding additional, client specified routes"
if [ -n "${ADDITIONAL_ROUTES}" ]; then
	for add_net in ${ADDITIONAL_ROUTES//,/ }; do
	    network=`parse_network ${add_net}`
	    echo "push \"route ${network}\"" >> $SERVER_CONF
        iptables -t nat -A POSTROUTING -s ${NETWORK} \
	       -d $add_net -o ${IFACE} -j MASQUERADE
	done
fi

# Run as unpriviliged user
sed -i -e "s/;user nobody/user nobody/g" $SERVER_CONF
sed -i -e "s/;group nogroup/group nogroup/g" $SERVER_CONF


# enable packet forwarding
echo 1 > /proc/sys/net/ipv4/ip_forward
sed -i -e "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g" /etc/sysctl.conf


# Configure easy-rsa
export KEY_COUNTRY=`config-get key-country`
export KEY_PROVINCE=`config-get key-province`
export KEY_CITY=`config-get key-city`
export KEY_ORG=`config-get key-org`
#export KEY_OU=`config-get key-ou`
export DOMAIN=`config-get domain`
if [ -z "$DOMAIN" ]; then
  export DOMAIN=$(hostname)
fi
export KEY_EMAIL=`webmaster@${DOMAIN}`


cp -r /usr/share/easy-rsa/ /etc/openvpn
mkdir -p /etc/openvpn/easy-rsa/keys
sed -i -e "s/export KEY_COUNTRY=\".*\"/export KEY_COUNTRY=\"$KEY_COUNTRY\"/g" /etc/openvpn/easy-rsa/vars
sed -i -e "s/export KEY_PROVINCE=\".*\"/export KEY_PROVINCE=\"$KEY_PROVINCE\"/g" /etc/openvpn/easy-rsa/vars
sed -i -e "s/export KEY_CITY=\".*\"/export KEY_CITY=\"$KEY_CITY\"/g" /etc/openvpn/easy-rsa/vars
sed -i -e "s/export KEY_ORG=\".*\"/export KEY_ORG=\"$KEY_ORG\"/g" /etc/openvpn/easy-rsa/vars
sed -i -e "s/export KEY_EMAIL=\".*\"/export KEY_EMAIL=\"$KEY_EMAIL\"/g" /etc/openvpn/easy-rsa/vars
sed -i -e "s/export KEY_OU=\".*\"/export KEY_OU=\"$KEY_OU\"/g" /etc/openvpn/easy-rsa/vars


# Build server keys and certs
cd /etc/openvpn/easy-rsa
source ./vars
./clean-all
# build diffie-Hellman keys
/etc/openvpn/easy-rsa/build-dh
# what ./build-ca does
/etc/openvpn/easy-rsa/pkitool --initca
# what ./build-key does
/etc/openvpn/easy-rsa/pkitool --server $DOMAIN

cp /etc/openvpn/easy-rsa/keys/{${DOMAIN}.crt,${DOMAIN}.key,ca.crt,dh2048.pem} /etc/openvpn/

sed -i -e "s/cert server.crt/cert ${DOMAIN}.crt/g" $SERVER_CONF
sed -i -e "s/key server.key/key ${DOMAIN}.key/g" $SERVER_CONF

# Create client config template
cp /usr/share/doc/openvpn/examples/sample-config-files/client.conf /etc/openvpn/client.ovpn
echo "ca ca.crt
cert client.crt
key client.key" >> /etc/openvpn/client.ovpn
