"options":
  "extra_packages":
    "description": "Space separated list of extra deb packages to install.\n"
    "type": "string"
    "default": ""
  "package_status":
    "default": "install"
    "type": "string"
    "description": "The status of service-affecting packages will be set to this value\
      \ in the dpkg database. Valid values are \"install\" and \"hold\".\n"
  "install_sources":
    "description": "List of extra apt sources, per charm-helpers standard format (a\
      \ yaml list of strings encoded as a string). Each source may be either a line\
      \ that can be added directly to sources.list(5), or in the form ppa:<user>/<ppa-name>\
      \ for adding Personal Package Archives, or a distribution component to enable.\n"
    "type": "string"
    "default": ""
  "install_keys":
    "description": "List of signing keys for install_sources package sources, per\
      \ charmhelpers standard format (a yaml list of strings encoded as a string).\
      \ The keys should be the full ASCII armoured GPG public keys. While GPG key\
      \ ids are also supported and looked up on a keyserver, operators should be aware\
      \ that this mechanism is insecure. null can be used if a standard package signing\
      \ key is used that will already be installed on the machine, and for PPA sources\
      \ where the package signing key is securely retrieved from Launchpad.\n"
    "type": "string"
    "default": ""
  "install-type":
    "type": "string"
    "default": "jre"
    "description": |
      Override of the install-type. NOT TO BE ADJUSTED.
  "java-major":
    "type": "string"
    "default": "8"
    "description": |
      Override of the java-major. NOT TO BE ADJUSTED.
  "java-flavor":
    "type": "string"
    "default": "oracle"
    "description": |
      Override of the java-flavor. NOT TO BE ADJUSTED.
  "emulab-cert":
    "type": "string"
    "default": "VGhpcyBpcyB0aGUgZGVmYXVsdCBjZXJ0aWZpY2F0ZSB2YWx1ZS4gUGxlYXNlIGNoYW5nZSBtZSBiZWZvcmUgdXNlCg=="
    "description": "Emulab certificate (BASE64 encoded)"
  "emulab-cert-pass":
    "type": "string"
    "default": "This is the default password value. Please change me before use."
    "description": "Password of the emulab certificate"
