#!/bin/bash -e

export JAVA_HOME_7=/usr/lib/jvm/java-7-openjdk-amd64

installPackages()
{
	juju-log "Installing Packages";
	apt-get -y install git
	apt-get -y install maven
	apt-get -y install openjdk-7-jdk	
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	if [ ! -d "/tmp/storm-topology/$serviceName" ]; then
		juju-log "Creating /tmp/storm-topology/$serviceName"
		juju-log "$workingDir"
		mkdir -p /tmp/storm-topology/$serviceName
		cd /tmp/storm-topology/$serviceName
		git clone https://github.com/xannz/Storm-Flux-Skeleton.git
		echo "name: \"$serviceName\"" > /tmp/storm-topology/$serviceName/topology.yaml
		echo "config:" >> /tmp/storm-topology/$serviceName/topology.yaml
		echo "  topology.workers: 1" >> /tmp/storm-topology/$serviceName/topology.yaml
		touch /tmp/storm-topology/$serviceName/spouts
		touch /tmp/storm-topology/$serviceName/bolts
		touch /tmp/storm-topology/$serviceName/graph
		touch /tmp/storm-topology/$serviceName/classes
		echo "0" > /tmp/storm-topology/$serviceName/rebuild
		if [ ! -f /tmp/storm-topology/buildGraph ]; then
			juju-log "Setting buildGraph"
			cp "$workingDir/files/buildGraph" /tmp/storm-topology/
			chmod 744 /tmp/storm-topology/buildGraph
		fi
		cd /tmp/storm-topology/$serviceName/Storm-Flux-Skeleton 
		mvn clean install -DskipTests=true		
	fi	
	status-set blocked "Waiting for topology name"
}

setName()
{
	name=`config-get name`
	juju-log "Setting name $name"
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	sed -i "1s/.*/name: \"$name\"/" /tmp/storm-topology/$serviceName/topology.yaml
	status-set active
}

topologyChanged()
{
	juju-log "topo changed"
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	juju-log "serviceName: $serviceName"
	relation-set serviceName=$serviceName
}


cmd=$(basename "$0")
case $cmd in
config-changed)	
	setName
	;;
start)
	;;
stop)
	;;
install)
	installPackages
	;;
upgrade-charm)
	;;
topology-relation-changed)
	topologyChanged
	;;
esac
