options:
  name:
    type: string
    description: "Spout name (Unique in the topology)"
  class:
    type: string
    description: "Spout class Example: storm.kafka.KafkaSpout"
  spoutURL:
    type: string
    description: "URL to spout location"
    

