options:
  class:
    type: string
    default:    
    description: |
      URL to the bolt class
  prepare-methods:
    type: string
    default:    
    description: |
      Methods to prepare bolt, example: method1(param,param);method2(param)
  groupings:
    type: string
    default:
    description: |
      All non SHUFFLE groupings go here: otherBolt(FIELDS word);otherSpout(ALL)
  database:
    type: string
    default:
    description: |
      Name of MongoDB database for mongodb bolt

