options:
  emulab-s4-cert:
    type: string
    default: "VGhpcyBpcyB0aGUgZGVmYXVsdCBjZXJ0aWZpY2F0ZSB2YWx1ZS4gUGxlYXNlIGNoYW5nZSBtZSBiZWZvcmUgdXNlCg=="
    description: "Emulab speaksfor certificate (BASE64 encoded)"
  emulab-project-name:
    type: string
    default: "tengu"
    description: "Password of the emulab certificate"
  bundle:
    type: string
    default:
    description: bundle to deploy after setup
  user:
    type: string
    default: ubuntu
    description: user to install the tools for
  hauchiwa-flavor:
    type: string
    default: ssh
    description: flavor of the installed hauchiwa
  charm-repo-source:
    type: string
    description: Git url where charm repo resides. Expects charm repo in <repo_root>/charms.
    default: "http://github.com/tvanhove/tengu-charms.git"