options:
  emulab-s4-cert:
    type: string
    default: "VGhpcyBpcyB0aGUgZGVmYXVsdCBjZXJ0aWZpY2F0ZSB2YWx1ZS4gUGxlYXNlIGNoYW5nZSBtZSBiZWZvcmUgdXNlCg=="
    description: Emulab speaksfor certificate (BASE64 encoded).  This config value is being deprecated.
  emulab-project-name:
    type: string
    default: "tengu"
    description: Name of the emulab project.  This config value is being deprecated.
  bundle:
    type: string
    default:
    description: bundle to deploy after setup
  init-bundle:
    type: string
    default:
    description: this replaces the default init-bundle
  user:
    type: string
    default: ubuntu
    description: user to install the tools for
  hauchiwa-flavor:
    type: string
    default: rest2jfed
    description: |
      flavor of the installed hauchiwa. Possible values: ['rest2jfed', 'ssh']. This config value is being deprecated.
  charm-repo-source:
    type: string
    description: Git url where charm repo resides. Expects charm repo in <repo_root>/charms.
    default:
  feature-flags:
    type: string
    default: ''
    description: |
      Comma-delimited list of feature flags to be used. Each feature flag specified is set to 'True'. Example: 'DEBUG,FEATURE_FLAG_AUTH'. (non-conclusive) List of supported flags:
        - DEBUG: run h_api in debug mode
        - FEATURE_FLAG_AUTH: Turn on authentication on h_api
  providerconfig:
    type: string
    default: ''
    description: |
      Json object that contains the authentication and provider config that this hauchiwa will use. Example:
        {
          "env-configs": {
            "type": "maas",
            "maas-oauth": "MAAS-API-KEY",
            "maas-server": "http://<my-maas-server>:80/MAAS"
          }
        }
