options:
  emulab-s4-cert:
    type: string
    default: "VGhpcyBpcyB0aGUgZGVmYXVsdCBjZXJ0aWZpY2F0ZSB2YWx1ZS4gUGxlYXNlIGNoYW5nZSBtZSBiZWZvcmUgdXNlCg=="
    description: "Emulab speaksfor certificate (BASE64 encoded)"
  emulab-project-name:
    type: string
    default: "tengu"
    description: "Password of the emulab certificate"
  bundle:
    type: string
    default:
    description: bundle to deploy after setup
  user:
    type: string
    default: ubuntu
    description: user to install the tools for
  hauchiwa-flavor:
    type: string
    default: rest2jfed
    description: |
      flavor of the installed hauchiwa. Possible values: ['rest2jfed', 'ssh']
  charm-repo-source:
    type: string
    description: Git url where charm repo resides. Expects charm repo in <repo_root>/charms.
    default: "http://github.com/galgalesh/tengu-charms.git"
