"options":
  "extra_packages":
    "description": "Space separated list of extra deb packages to install.\n"
    "type": "string"
    "default": ""
  "package_status":
    "default": "install"
    "type": "string"
    "description": "The status of service-affecting packages will be set to this value\
      \ in the dpkg database. Valid values are \"install\" and \"hold\".\n"
  "install_sources":
    "description": "The repository to install Debian packages from."
    "type": "string"
    "default": "deb http://debian.neo4j.org/repo stable/"
  "install_keys":
    "description": "The key for the Debian package repository."
    "type": "string"
    "default": "01182252"
  "python-type":
    "type": "string"
    "default": "neo4j-driver"
    "description": "This option will install a neo4j python driver. Supported drivers\
      \ are Neo4J python driver(neo4j-driver) \nand Py2Neo(py2neo). Set to none if\
      \ no driver has to be installed.\n"
