options:
  key-country:
    type: string
    default: "US"
    description: Country field for RSA certificate.
  key-province:
    type: string
    default: "CA"
    description: Province field for RSA certificate.
  key-city:
    type: string
    default: "Ubuntu"
    description: City field for RSA certificate.
  key-org:
    type: string
    default: "Juju"
    description: Organization field for RSA certificate.
  key-email:
    type: string
    default: "Juju"
    description: Email field for RSA certificate.
  clients:
    type: string
    default: "client1"
    description: Space-separated list with names of users to generate config for.
  port:
    type: int
    default: 443
    description: Port for VPN traffic. Default is 443 since it isn't likely to be blocked by the firewall.
  protocol:
    type: string
    default: tcp
    description: Protocol for VPN communication (tcp|udp). Tcp on port 443 is least likely to be blocked by firewalls. Udp on port 1194 is fastest.
  duplicate-cn:
    type: boolean
    default: True
    description: Will multiple users connect using the same client config? (yes = True)
  push-dns:
    type: boolean
    default: True
    description: Should the connecting clients use the same DNS and search domain as the OpenVPN server? (yes = True)
  push-default-gateway:
    type: boolean
    default: True
    description: |
      Should the connecting clients use the VPN server for ALL connections? (yes = True) If this is False, the VPN will only be used for connections to the internal network. Connections to the internet will still use the client's existing non-vpn connection.
