#!/bin/bash -e


installPackages()
{
	juju-log "Installing Packages"
	apt-get -y install git
	apt-get -y install maven
	apt-get -y install openjdk-7-jdk	
	if [ ! -d "/tmp/storm-topology" ]; then
		juju-log "Creating /tmp/storm-topology"
		mkdir -p /tmp/storm-topology
	fi
	if [ ! -f "/tmp/storm-topology/spout-list" ]; then
		juju-log "Creating spout-list"
		touch /tmp/storm-topology/spout-list
	fi
	status-set blocked "Waiting for: spout class"
}

#test meerdere spouts uit in file /tmp/storm-topology/spout-list en /tmp/storm-topology/topo1/spouts
getSpout()
{
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topology=`grep "^$serviceName" /tmp/storm-topology/spout-list | cut -d " " -f 2`
	if [ -n "$topology" ]; then			
		className=${1##*/}
		classNoExtension=`echo $className | cut -d \. -f1`
		if [ ! -f /tmp/storm-topology/$topology/Storm-Flux-Skeleton/src/main/java/tengu/storm/$className ]; then
			juju-log "Downloading spout class"
			wget -nc $1 /tmp/storm-topology/$topology/Storm-Flux-Skeleton/src/main/java/tengu/storm/$className
		fi		
		echo "$serviceName $classNoExtension" >> /tmp/storm-topology/$topology/spouts
		status-set active
	fi	
}

checkSettings()
{
	spoutClass=`config-get class`
	#juju-log "spoutClass: $spoutClass  exitcode: $?"
	if [ -n "$spoutClass" ]; then
		juju-log "Getting class"
		getSpout $spoutClass
	else
		juju-log "spout class required"
		status-set blocked "Waiting for class"
	fi
}

topologyChanged()
{
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topologyName=`relation-get serviceName`
	juju-log "Topology name is: $topologyName"	
	if grep -q "^$serviceName" /tmp/storm-topology/spout-list ; then
		hulp=$(sed "s/^$serviceName.*/$serviceName $topologyName/" /tmp/storm-topology/spout-list)
		juju-log "Copy spout-list: "
		juju-log "$hulp"
		echo "$hulp" > /tmp/storm-topology/spout-list
	else
		juju-log "Spout not found in spout-list ... adding"
		echo "$serviceName $topologyName" >> /tmp/storm-topology/spout-list
	fi
}

stormelementChanged()
{
	juju-log "stormelement relation changed"	
	serviceName=`[[ "$(pwd)" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	relation-set elementName=$serviceName
	topology=`grep "^$serviceName" /tmp/storm-topology/spout-list | cut -d " " -f 2`
	element=`relation-get elementName`
	if [ -n "$element" ]; then
		juju-log "Connected to: $element"
		#check if already in graph
		( grep -w "$serviceName" /tmp/storm-topology/$topology/graph | grep -wq "$element" ) || echo "$serviceName $element SHUFFLE" >> /tmp/storm-topology/$topology/graph
		#deploy new graph 
		sh /tmp/storm-topology/buildGraph $topology
	fi
}

cmd=$(basename "$0")
case $cmd in
config-changed)
	checkSettings
	;;
start)
	;;
stop)
	;;
install)
	installPackages
	;;
upgrade-charm)
	;;
topology-relation-changed)
	juju-log "Hook running topology-relation-changed"
	topologyChanged
	;;
stormelement-relation-changed)
	stormelementChanged
	;;
esac
