#!/bin/bash -e


installPackages()
{
	juju-log "Installing Packages"
	apt-get -y install git
	apt-get -y install maven
	apt-get -y install openjdk-7-jdk	
	if [ ! -d "/tmp/storm-topology" ]; then
		juju-log "Creating /tmp/storm-topology"
		mkdir -p /tmp/storm-topology
	fi
	if [ ! -f "/tmp/storm-topology/spout-list" ]; then
		juju-log "Creating spout-list"
		touch /tmp/storm-topology/spout-list
	fi
	status-set blocked "Waiting for: spout name; spout class"
}

getSpout()
{
	juju-log "Downloading spout class"
	wget $1 /tmp/storm-topology/spouts/$2.java
	status-set active
}

importSpout()
{
	status-set active
}

checkSettings()
{
	spoutName=`config-get name`
	spoutClass=`config-get spoutClass`
	spoutURL=`config-get spoutURL`
	waitingFor=""
	if [ -w spoutName ];then
		waitingFor="$waitingFor; spout name"
	fi
	if [[ -w spoutClass && -w spoutURL  ]];then
		waitingFor="$waitingFor; spout class"
	fi
	if [ ! -w waitingFor ];then
		status-set blocked "Waiting for $waitingFor"
	else
		if [ -w spoutClass ];then
			getSpout $spoutURL $spoutName
		else
			importSpout $spoutClass $spoutName		
		fi	
	fi
}

topologyChanged()
{
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topologyName=`relation-get serviceName`
	juju-log "Topology name is: $topologyName"	
	grep -q "^$serviceName" /tmp/storm-topology/spout-list && sed --quiet "s/^spout.*/spout topology/" /tmp/storm-topology/spout-list || echo "$serviceName $topologyName" >> /tmp/storm-topology/spout-list
}

cmd=$(basename "$0")
case $cmd in
config-changed)
	checkSettings
	;;
start)
	;;
stop)
	;;
install)
	installPackages
	;;
upgrade-charm)
	;;
topology-relation-changed)
	topologyChanged
	;;
esac
