#!/bin/bash
# Copyright (C) 2016  Ghent University
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

apt-get install -y git openjdk-7-jre tree

# Build gobblin
cd /opt/
git clone https://github.com/linkedin/gobblin.git
cd gobblin
./gradlew clean build
mkdir job-config
mkdir work-dir
mkdir logs

# Install gobblin
#exit 1
#tar -zxvf gobblin-dist.tar.gz
#cd gobblin-dist

# Start gobblin
export JAVA_HOME='/usr/lib/jvm/java-7-openjdk-amd64'
export GOBBLIN_WORK_DIR='/opt/gobblin-dist/work-dir'
export GOBBLIN_JOB_CONFIG_DIR='/opt/gobblin-dist/job-config'
export GOBBLIN_LOG_DIR='/opt/gobblin-dist/logs'
#/opt/gobblin-dist/bin/gobblin-standalone.sh start
# java -jar avro-tools-1.7.7.jar tojson --pretty  > output.json
# Stop gobblin
#bin/gobblin-standalone.sh stop
