options:
  maas-username:
    type: string
    default: ""
    description: "Username of maas user with admin privileges."
  maas-pass:
    type: string
    default: ""
    description: "Corresponding password."
  maas-url:
    type: string
    default: "http://localhost/MAAS/api/1.0/"
    description: "Url to maas API"
