#!/bin/bash -e


installPackages()
{
	juju-log "Installing Packages"
	apt-get -y install git
	apt-get -y install maven
	apt-get -y install openjdk-7-jdk	
	if [ ! -d "/tmp/storm-topology" ]; then
		juju-log "Creating /tmp/storm-topology"
		mkdir -p /tmp/storm-topology
	fi
	if [ ! -f "/tmp/storm-topology/spout-list" ]; then
		juju-log "Creating spout-list"
		touch /tmp/storm-topology/spout-list
	fi
	status-set blocked "Waiting for: kafka configuration"
}

getKafkaConfig()
{
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topology=`grep "^$serviceName" /tmp/storm-topology/spout-list | cut -d " " -f 2`
	className=${1##*/}
	if [ -n "$topology" ]; then				
		juju-log "Downloading kafka-spout config"	
		wget -O /tmp/storm-topology/$topology/kafka-config "$1"
		grep -wq "$serviceName" /tmp/storm-topology/$topology/spouts || echo "$serviceName storm.kafka.KafkaSpout" >> /tmp/storm-topology/$topology/spouts		
		status-set active
	fi	
}

setKafkaConfigName()
{
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topology=`grep "^$serviceName" /tmp/storm-topology/spout-list | cut -d " " -f 2`	
	grep -qw "$serviceName" /tmp/storm-topology/$topology/kafka-spout-config && sed -i "s/^$serviceName.*/$serviceName $1/" /tmp/storm-topology/$topology/kafka-spout-config || echo "$serviceName $1" >> /tmp/storm-topology/$topology/kafka-spout-config
}

checkSettings()
{
	kafkaConfig=`config-get config`
	spoutConfigName=`config-get spoutconfigname`
	if [[ -n "$kafkaConfig" || -n "$spoutConfigName" ]]; then
		if [ -n "$kafkaConfig" ]; then
			juju-log "Getting Kafka Config"
			getKafkaConfig $kafkaConfig
		fi
		
		if [ -n "$spoutConfigName" ]; then
			juju-log "Setting Kafka Spout Config Name"
			setKafkaConfigName $spoutConfigName
		fi
	else
		juju-log "Kafka config required"
		status-set blocked "Waiting for kafka configuration"
	fi
}

topologyChanged()
{
	workingDir=`pwd`
	serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topologyName=`relation-get serviceName`
	juju-log "Topology name is: $topologyName"	
	if grep -q "^$serviceName" /tmp/storm-topology/spout-list ; then
		hulp=$(sed "s/^$serviceName.*/$serviceName $topologyName/" /tmp/storm-topology/spout-list)
		juju-log "Copy spout-list: "
		juju-log "$hulp"
		echo "$hulp" > /tmp/storm-topology/spout-list
	else
		juju-log "Spout not found in spout-list ... adding"
		echo "$serviceName $topologyName" >> /tmp/storm-topology/spout-list
	fi
	#add POM dependency's  & kafka-spout-config file
	#Dependecy only for apache 0.10.0 
	#dependencies moet op 1 lijn met \n
	if [ -n "$topologyName" ]; then
		if ! grep "storm-kafka" /tmp/storm-topology/$topologyName/Storm-Flux-Skeleton/pom.xml; then 
			C=$(cat $workingDir/files/dependencies | sed 's/\//\\\//g')
			sed -i "/<\/dependencies>/ s/.*/${C}\n&/" /tmp/storm-topology/$topologyName/Storm-Flux-Skeleton/pom.xml
		fi
		if [ ! -f /tmp/storm-topology/$topologyName/kafka-spout-config ]; then
			touch /tmp/storm-topology/$topologyName/kafka-spout-config
		fi
		#copy KafkaBoltKeyValueScheme.java
		if [ ! -f /tmp/storm-topology/$topologyName/Storm-Flux-Skeleton/src/main/java/tengu/storm/KafkaBoltKeyValueScheme.java ]; then
			cp "$workingDir/files/KafkaBoltKeyValueScheme.java" /tmp/storm-topology/$topologyName/Storm-Flux-Skeleton/src/main/java/tengu/storm/
			echo "1" > /tmp/storm-topology/$topology/rebuild
		fi
	fi
	

}

stormelementChanged()
{
	juju-log "stormelement relation changed"
	serviceName=`[[ "$(pwd)" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	relation-set elementName=$serviceName
	topology=`grep "^$serviceName" /tmp/storm-topology/spout-list | cut -d " " -f 2`
	element=`relation-get elementName`	
}

stormelementDeparted()
{
	serviceName=`[[ "$(pwd)" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topology=`grep "^$serviceName" /tmp/storm-topology/spout-list | cut -d " " -f 2`
	element=`relation-get elementName`
	juju-log "Relation broken with $element"
}

zookeeperChanged()
{
## TODO?: save zookeeper in lokale file tot topology.yaml is aangemaakt?

	juju-log "Zookeeper relation found"
	privateIp=`relation-get private-address`
	port=`relation-get port`	
	if [[ -n "$privateIp" && -n "$port" ]]; then
		juju-log "Zookeeper ip: $privateIp:$port"
		workingDir=`pwd`
		serviceName=`[[ "$workingDir" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
		topology=`grep "^$serviceName" /tmp/storm-topology/spout-list | cut -d " " -f 2`
		#check of configArgs er al is zo ja aanpassen anders erbij plaatsen
		#Assumes kafka-config is already present
		lijnnr=$(grep -n ".*ZkHosts\"" /tmp/storm-topology/$topology/kafka-config | cut -d ":" -f 1)
		((lijnnr++))
		if [[ $(head -n $lijnnr "/tmp/storm-topology/$topology/kafka-config" | tail -n 1) =~ "constructorArgs:" ]]; then
			regex="[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\:[0-9]+"
			((lijnnr++))
			if [[ "$(head -n $lijnnr "/tmp/storm-topology/$topology/kafka-config" | tail -n 1)" =~ $regex ]]; then
				#overwrite
				sed -i "$lijnnr/.*/\ \ \ \ \ \ - \"$privateIp:$port\"/" /tmp/storm-topology/$topology/kafka-config
			else
				#insert ip
				sed -i "${lijnnr}i\ \ \ \ \ \ - \"$privateIp:$port\"" /tmp/storm-topology/$topology/kafka-config
			fi
		else
			#insert constructArgs & ip
			sed -i "${lijnnr}i\ \ \ \ constructorArgs:" /tmp/storm-topology/$topology/kafka-config
			((lijnnr++))
			sed -i "${lijnnr}i\ \ \ \ \ \ - \"$privateIp:$port\"" /tmp/storm-topology/$topology/kafka-config
		fi
	fi
}

topologyDeparted()
{
	serviceName=`[[ "$(pwd)" =~ unit-(.+)- ]] && echo ${BASH_REMATCH[1]}`
	topology=`grep "^$serviceName" /tmp/storm-topology/spout-list | cut -d " " -f 2`
	juju-log "Topology departed"
	#remove spout from topologyName/spouts
	sed -i "/^$serviceName\b/d" /tmp/storm-topology/$topology/spouts
	#remove spout from storm-topology/spout-list
	sed -i "/^$serviceName\b/d" /tmp/storm-topology/spout-list
	#remove spout from kafka-spout-config
	sed -i "/^$serviceName\b/d" /tmp/storm-topology/kafka-spout-config
}

cmd=$(basename "$0")
case $cmd in
config-changed)
	checkSettings
	;;
start)
	;;
stop)
	;;
install)
	installPackages
	;;
upgrade-charm)
	;;
topology-relation-changed)
	juju-log "Hook running topology-relation-changed"
	topologyChanged
	;;
stormelement-relation-changed)
	stormelementChanged
	;;
stormelement-relation-departed)
	stormelementDeparted
	;;
zookeeper-relation-changed)
	zookeeperChanged
	;;
topology-relation-departed)
	topologyDeparted
	;;
esac
