#!/bin/bash
set -ex
NUM_PARTITIONS=`action-get partitions`

# create dir to store results
RUN=`date +%s`
RESULT_DIR=/opt/sparkpi-results
RESULT_LOG=${RESULT_DIR}/${RUN}.log
mkdir -p ${RESULT_DIR}
chown -R ubuntu:ubuntu ${RESULT_DIR}

benchmark-start
START=`date +%s`
# NB: Escaped vars in the block below (e.g., \${MASTER}) come from
# /etc/environment while non-escaped vars (e.g., ${NUM_PARTITIONS}) are
# parameterized from this outer scope
su ubuntu << EOF
. /etc/environment
echo 'calculating pi'
spark-submit --master \${MASTER} --class org.apache.spark.examples.SparkPi \
  /usr/lib/spark/lib/spark-examples-*.jar ${NUM_PARTITIONS} &> ${RESULT_LOG}
EOF
STOP=`date +%s`
benchmark-finish

DURATION=`expr $STOP - $START`
benchmark-composite "${DURATION}" 'secs' 'asc'
benchmark-raw ${RESULT_LOG}
