options:
  type:
    type: string
    default: "default"
    description: "type of the model"
  tag:
    type: string
    default: ""
    description: "tag of the model"
  moreinfo:
    type: string
    default: ""
    description: "More info about the model"
  semver:
    type: string
    default: "1.0.0"
    description: "Version of this model, see semver.org"
