options:
  database:
    type: string
    default: "testdb"
    description: |
      Name of the PostgreSQL database that the segment will connect to.
  username:
    type: string
    default:
    description: |
      Username to connect to database.
  password:
    type: string
    default:
    description: |
      password to connect to database.
  installable-id:
    type: string
    default: "org.ibcn.limeds.influxdb"
    description: |
      Id of the PostgreSQL connector installable. List of available installables: http://limeds.be/installables.
  installable-version:
    type: string
    default: "latest"
    description: |
      Version of the PostgreSQL connector installable. List of available installables: http://limeds.be/installables.
  segment-id:
    type: string
    default: "io.tengu.limeds.PostgreSQL"
    description: |
      Id of the PostgreSQL segment that will be created in LimeDS. Your slices can refer to the segment using this id.
