/*
  Copyright (C) 2016  Ghent University

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.


  This file is the Jenkins Pipeline script for the CI pipeline for the Tengu charms.
*/
node {
  echo 'Pipeline Start'
  stage 'Checkout'
  git url: 'https://github.com/IBCNServices/tengu-charms/'
  env.JUJU_REPOSITORY = pwd() + '/charms'
  echo "previous succesfull commit: ${env}"
  def resultsDir = "/var/www/html"

  stage 'Download Bigfiles'
  //sh 'tengu downloadbigfiles'
  // workaround for https://bugs.launchpad.net/juju/+bug/1592822
  //sh 'rm charms/trusty/rest2jfed/files/jfedS4/jfed_cli.tar.gz'
  //sh 'rm charms/trusty/rest2jfed/files/jdk-8u77-linux-x64.tar.gz'
  /*
    The next stage assumes that `charm login` is already executed and access is
    granted to the channels:

        charm grant cs:~tengu-bot/trusty/hauchiwa everyone --channel development
        charm grant cs:~tengu-bot/trusty/rest2jfed everyone --channel development
  */
  stage 'Run Tests'

  sh("exit 1")
  stormTestDir = readFile('testdir').trim() //workaround for https://issues.jenkins-ci.org/browse/JENKINS-26133


  stage 'Test'
  sh("./cihelpers.py test '${stormTestDir}' '${resultDir}'")
}
