"options":
  "resources_mirror":
    "type": "string"
    "default": ""
    "description": |
      URL from which to fetch resources (e.g., Hadoop binaries) instead of Launchpad.
  "hue-version":
    "type": "string"
    "default": "3.9.0"
    "description": "HUE version - for IBM POWER set to ??"
