options:
  install_sources:
    type: string
    description: The repository to install Debian packages from.
    default: deb http://debian.neo4j.org/repo stable/
  install_keys:
    type: string
    description: The key for the Debian package repository.
    default: "01182252"
  port:
    type: int
    default: 7474
    description: "Port that is used to navigate to Neo4J"
  auth:
    type: string
    default: "neo4j/neo4j"
    description: "Authentication, set to none to disable authentication or neo4j/<password> to override the default."
  java-flavor:
    type: string
    default: "openjdk"
    description: |
      Override of the java-flavor. NOT TO BE ADJUSTED.
  install-type:
    type: string
    default: "full"
    description: |
      Override of the install-type. NOT TO BE ADJUSTED.
  java-major:
    type: string
    default: "8"
    description: |
      Override of the java-major. NOT TO BE ADJUSTED.
