options:
  domain:
    type: string
    default: ""
    description: FQDN of the server, defaults to unit's given hostname
  port:
    type: int
    default: 8080
    description: port for VPN traffic. Default is 8080(HTTP2) since it isn't likely to be used by the server or blocked by the firewall.
  protocol:
    type: string
    default: tcp
    description: protocol for VPN communication (tcp|udp). Tcp on port 443 is least likely to be blocked by firewalls. Udp on port 1194 is fastest.
  key-country:
    type: string
    default: "US"
    description: country field for RSA certificate
  key-province:
    type: string
    default: "CA"
    description: province field for RSA certificate
  key-city:
    type: string
    default: "Ubuntu"
    description: city field for RSA certificate
  key-org:
    type: string
    default: "Juju"
    description: organization field for RSA certificate
  network:
    type: string
    default: "192.168.14.0 255.255.255.0"
    description: Network that vpn users should be able to connect to. A route to this network will be pushed to clients.
