options:
  domain:
    type: string
    default: ""
    description: FQDN of the server, defaults to unit's given hostname
  port:
    type: int
    default: 443
    description: port for VPN traffic
  protocol:
    type: string
    default: tcp
    description: protocol for VPN communication (tcp|udp). Tcp on port 443 is less likely to be blocked by firewalls. Udp on port 1194 is faster.
  key-country:
    type: string
    default: "US"
    description: country field for RSA certificate
  key-province:
    type: string
    default: "CA"
    description: province field for RSA certificate
  key-city:
    type: string
    default: "Ubuntu"
    description: city field for RSA certificate
  key-org:
    type: string
    default: "Juju"
    description: organization field for RSA certificate
