#!/bin/bash -e

stormdeployerjar=/opt/storm/stormdeployer/stormdeployer.jar
export JAVA_HOME_7=/usr/lib/jvm/java-7-openjdk-amd64

deploy()
{
	deploys=`config-get deploy`
	credentials=`config-get credentials`
	(IFS=','; for deployconfig in $deploys; do deploy_url "$deployconfig" "$credentials"; done)
}

deploy_url()
{
	juju-log "deploying $1 (credentials: $2)"
        $JAVA_HOME_7/bin/java -cp $stormdeployerjar com.ubuntu.stormdeployer.StormDeployer $1 $2 /opt/storm/latest/logs/deploy.log
       
}

undeploy()
{
	undeploys=`config-get undeploy`
	(IFS=','; for undeployconfig in $undeploys; do undeploy_topology "$undeployconfig"; done)
}

undeploy_topology()
{
     	$JAVA_HOME_7/bin/java -cp $stormdeployerjar com.ubuntu.stormdeployer.StormUndeployer $1 /opt/storm/latest/logs/deploy.log
        
}

installPackages()
{
	apt-get -y install git
	apt-get -y install maven
	apt-get -y install openjdk-7-jdk
        mkdir -p /opt/storm/stormdeployer/
        cd /opt/storm
        rm -rf /opt/storm/StormCharmConnector
	git clone https://github.com/xannz/StormCharmConnector
	cd /opt/storm/StormCharmConnector	
	mvn package
	if [ ! -L $stormdeployerjar ]; then
        	ln -s /opt/storm/StormCharmConnector/target/stormcharmconnector-0.0.1-SNAPSHOT-jar-with-dependencies.jar $stormdeployerjar
	fi

}

cmd=$(basename "$0")
case "$cmd" in
config-changed)
	juju-log "config has changed"
	deploy
	undeploy
	;;
install)
	installPackages
	;;
upgrade-charm)
	installPackages
	;;
start)
	;;
stop)
	;;
esac
