options:
  charm-repo-source:
    type: string
    description: Git url where charm repo resides. Expects charm repo in <repo_root>/charms.
    default:
  environment-name:
    type: string
    description: Name of the environment to configure
    default:
  environment-config:
    type: string
    description: base64 encoded environment config from environments.yaml
    default:
  environment-jenv:
    type: string
    description: base64 encoded environment.jenv file
    default:
  environment-pubkey:
    type: string
    description: base64 encoded pubkey file
    default:
  environment-privkey:
    type: string
    description: base64 encoded privkey file
    default:
  ssh-keys:
    type: string
    description: a comma-seperated list of public ssh keys to add to the default (admin)
      user. The keys must be in the authorized-keys format. "ssh-rsa <key> <comment>".
    default:
  emulab-s4-cert:
    type: string
    default: VGhpcyBpcyB0aGUgZGVmYXVsdCBjZXJ0aWZpY2F0ZSB2YWx1ZS4gUGxlYXNlIGNoYW5nZSBtZSBiZWZvcmUgdXNlCg==
    description: Emulab speaksfor certificate (BASE64 encoded)
  emulab-project-name:
    type: string
    default: This is the default project value. Please change me before use.
    description: Password of the emulab certificate
