"options":
  "apt":
    "packages":
    - "docker.io"
    "version_package": ""
    "full_version": !!bool "false"
  "docker": {}
  "basic":
    "use_venv": !!bool "false"
    "packages": []
    "include_system_packages": !!bool "false"
"includes":
- "layer:basic"
- "layer:apt"
- "interface:docker-image-host"
"repo": "git@github.com:IBCNServices/layer-docker.git"
"exclude":
- "tests/10-deploy.py"
- "tests/tests.yaml"
"is": "docker"
